on:
  workflow_dispatch:
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 21 20 * * *
name: Semgrep
jobs:
  semgrep:
    name: Scan
    runs-on: ${{ matrix.os }}   
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18]
      fail-fast: false
    env:
      CYCLONEDX_NPM_VERSION: '^2.0.0||^3.0.0'
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}       
    container:
      image: returntocorp/semgrep      
    steps:
      - name: "Check out Git repository"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - name: "Use Node.js ${{ matrix.node-version }}"
        if: ${{ success() }}
        uses: actions/setup-node@v4 #v4.1.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Install CLI tools"
        if: ${{ success() }}      
        run: |
          npm install -g grunt-cli
      - name: "Set packaging options for Grunt"
        if: ${{ success() }}      
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
          echo "PCKG_OS_NAME=win32" >> $GITHUB_ENV
          elif [ "$RUNNER_OS" == "macOS" ]; then
          echo "PCKG_OS_NAME=darwin" >> $GITHUB_ENV
          else
          echo "PCKG_OS_NAME=linux" >> $GITHUB_ENV
          fi
          echo "PCKG_CPU_ARCH=x64" >> $GITHUB_ENV
          echo "PCKG_NODE_VERSION=${{ matrix.node-version }}" >> $GITHUB_ENV
        shell: bash
      - name: "Build package-lock.json and scan"
        if: ${{ success() }}      
        run: apk add nodejs npm && npm install --package-lock --lockfile-version 2 && semgrep ci
